project:
  type: website

website:
  title: "Sadman Shafiq"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: https://github.com/SadmanShaf117/SadmanShafiq117.github.io
        text: "GitHub"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



