project:
  type: website

website:
  title: "Sadman Shafiq"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: https://SadmanShafiq117.github.io/
        text: "GitHub Website Link"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



